### ISSUE TITLE
Package failed in win10 16299

### ISSUE THREAD

**Issue by kenlost** [MicrosoftDocs/msix-docs.zh-cn#2]
[在此处输入反馈]
I use VS 2017 create a UWP project whose TargetPlatformMinVersion is set as 10.0.16299.0. 
Then I create app package.  the .appxupload package will crash at startup with exception:

0x00007FFF91669709 (KernelBase.dll) (codecs.exe 中)处有未经处理的异常: 0xE0434352 (参数: 0xFFFFFFFF80070002, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x00007FFF73D00000)。
0x00007FFF73D00000 is the address of clr.dll
---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e9757ffa-ccdb-e9f3-3f74-6f147dd04066
* Version Independent ID: 15b5e687-f04d-d893-81fe-8fc86b63fe2d
* Content: [打包 .MSIX 应用 - MSIX](https://docs.microsoft.com/zh-cn/windows/msix/package/packaging-uwp-apps)
* Content Source: [msix-src/package/packaging-uwp-apps.md](https://github.com/MicrosoftDocs/msix-docs.zh-cn/blob/live/msix-src/package/packaging-uwp-apps.md)
* Product: **msix**
* GitHub Login: @olprod

**Comment by srvbpigh** [comment]
Hello, @kenlost
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @kenlost, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/msix-docs/issues/141. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
